// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"
)

type UploadedVideo struct {
	ID          int64     `json:"id"`
	Title       string    `json:"title"`
	Filename    *string   `json:"filename"`
	ContentType string    `json:"contentType"`
	FileSize    int64     `json:"fileSize"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
	S3Key       *string   `json:"s3Key"`
	S3Url       *string   `json:"s3Url"`
}
