// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: uploaded_videos.sql

package db

import (
	"context"
)

const countUploadedVideos = `-- name: CountUploadedVideos :one
SELECT COUNT(*) FROM uploaded_videos
`

func (q *Queries) CountUploadedVideos(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUploadedVideos)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUploadedVideo = `-- name: CreateUploadedVideo :one
INSERT INTO uploaded_videos (title, filename, content_type, file_size)
VALUES ($1, $2, $3, $4)
RETURNING id, title, filename, content_type, file_size, created_at, updated_at
`

type CreateUploadedVideoParams struct {
	Title       string `json:"title"`
	Filename    string `json:"filename"`
	ContentType string `json:"contentType"`
	FileSize    int64  `json:"fileSize"`
}

func (q *Queries) CreateUploadedVideo(ctx context.Context, arg CreateUploadedVideoParams) (UploadedVideo, error) {
	row := q.db.QueryRow(ctx, createUploadedVideo,
		arg.Title,
		arg.Filename,
		arg.ContentType,
		arg.FileSize,
	)
	var i UploadedVideo
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Filename,
		&i.ContentType,
		&i.FileSize,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUploadedVideo = `-- name: DeleteUploadedVideo :exec
DELETE FROM uploaded_videos
WHERE id = $1
`

func (q *Queries) DeleteUploadedVideo(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteUploadedVideo, id)
	return err
}

const getUploadedVideoByFilename = `-- name: GetUploadedVideoByFilename :one
SELECT id, title, filename, content_type, file_size, created_at, updated_at FROM uploaded_videos
WHERE filename = $1
`

func (q *Queries) GetUploadedVideoByFilename(ctx context.Context, filename string) (UploadedVideo, error) {
	row := q.db.QueryRow(ctx, getUploadedVideoByFilename, filename)
	var i UploadedVideo
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Filename,
		&i.ContentType,
		&i.FileSize,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUploadedVideoByID = `-- name: GetUploadedVideoByID :one
SELECT id, title, filename, content_type, file_size, created_at, updated_at FROM uploaded_videos
WHERE id = $1
`

func (q *Queries) GetUploadedVideoByID(ctx context.Context, id int64) (UploadedVideo, error) {
	row := q.db.QueryRow(ctx, getUploadedVideoByID, id)
	var i UploadedVideo
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Filename,
		&i.ContentType,
		&i.FileSize,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUploadedVideos = `-- name: ListUploadedVideos :many
SELECT id, title, filename, content_type, file_size, created_at, updated_at FROM uploaded_videos
ORDER BY created_at DESC
`

func (q *Queries) ListUploadedVideos(ctx context.Context) ([]UploadedVideo, error) {
	rows, err := q.db.Query(ctx, listUploadedVideos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UploadedVideo
	for rows.Next() {
		var i UploadedVideo
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Filename,
			&i.ContentType,
			&i.FileSize,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUploadedVideo = `-- name: UpdateUploadedVideo :one
UPDATE uploaded_videos
SET title = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, title, filename, content_type, file_size, created_at, updated_at
`

type UpdateUploadedVideoParams struct {
	ID    int64  `json:"id"`
	Title string `json:"title"`
}

func (q *Queries) UpdateUploadedVideo(ctx context.Context, arg UpdateUploadedVideoParams) (UploadedVideo, error) {
	row := q.db.QueryRow(ctx, updateUploadedVideo, arg.ID, arg.Title)
	var i UploadedVideo
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Filename,
		&i.ContentType,
		&i.FileSize,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
